org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
kotlin.incremental=true
kotlin.caching.enabled=true
android.useAndroidX=true
android.enableJetifier=false
android.builtInKotlin=true
flutter.minSdkVersion=21
android.enableR8.fullMode=true
android.skipBuildDependencyValidation=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
